#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

set -e

. $CHARM_DIR/scripts/common-variables.sh

# juju-log "all relations:\n$(relation-get)"

MONGO_HOST=$(relation-get private-address)
MONGO_IP=$(dig +short ${MONGO_HOST})

if [ -z $MONGO_HOST ]; then juju-log "missing host addres"; exit 5; fi
if [ -z $MONGO_IP ] ; then juju-log "Could not get IP for host $MONGO_HOST"; exit 6; fi
juju-log "Database new host: $MONGO_HOST"

MONGO_HOST_NAME=$(config-get mongo-host-name)
if [ -z $MONGO_HOST_NAME ]; then juju-log "missing MONGO_HOST_NAME"; exit 666; fi

if [ $MONGO_HOST_NAME = "localhost" ]; then
  juju-log "the mms charm wont work if you call the host localhost"
  exit 5
fi

sed -i.bak "/${MONGO_HOST_NAME} */d" $HOSTS_FILE
juju-log "Adding host rec: \"${MONGO_IP}        ${MONGO_HOST_NAME}\""
echo "${MONGO_IP}        ${MONGO_HOST_NAME}" >> $HOSTS_FILE

LOG_DIR="/var/log/${SVC_NAME}"
mkdir -p ${LOG_DIR}
chown -R ${SVC_USER} ${LOG_DIR}

cat <<EOF > /etc/init/${SVC_NAME}.conf
#!upstart
description "${SVC_NAME}"
author      "${SVC_AUTHOR}"

env PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

respawn
start on runlevel [2345]
stop on runlevel [016]

setuid $SVC_USER
chdir "${SVC_HOME}"

script
    sh -l -c "nohup python agent.py 2>&1 | tee ${LOG_DIR}/${SVC_NAME}.log"
end script
EOF

juju-log "Restarting ${SVC_NAME}"
service "${SVC_NAME}" start || service "${SVC_NAME}" restart
juju-log "started ${SVC_NAME}"
