#!/bin/bash
# This hook is executed each time a charm is upgraded after the new charm
# contents have been unpacked
# Best practice suggests you execute the hooks/install and
# hooks/config-changed to ensure all updates are processed

set -e

. $CHARM_DIR/scripts/common-variables.sh

# juju-log "all relations:\n$(relation-get)"

MONGO_HOST=$(relation-get private-address)
MONGO_IP=$(dig +short ${MONGO_HOST})

if [ -z $MONGO_HOST ]; then juju-log "missing host addres"; exit 5; fi
if [ -z $MONGO_IP ] ; then juju-log "Could not get IP for host $MONGO_HOST"; exit 6; fi
juju-log "Database new host: $MONGO_HOST"

MONGO_HOST_NAME=$(config-get mongo-host-name)
if [ -z $MONGO_HOST_NAME ]; then juju-log "missing MONGO_HOST_NAME"; exit 666; fi

if [ $MONGO_HOST_NAME = "localhost" ]; then
  juju-log "the mms charm wont work if you call the host localhost"
  exit 5
fi

sed -i.bak "/${MONGO_HOST_NAME} */d" $HOSTS_FILE
juju-log "Adding host rec: \"${MONGO_IP}        ${MONGO_HOST_NAME}\""
echo "${MONGO_IP}        ${MONGO_HOST_NAME}" >> $HOSTS_FILE

LOG_DIR="/var/log/${SVC_NAME}"
mkdir -p ${LOG_DIR}
chown -R ${SVC_USER} ${LOG_DIR}

mkUpstart () {
  JOB_NAME=$1
  JOB_DIR=$2
  JOB_CMD=$3
  juju-log "mkUpstart ${JOB_NAME} with cmd ${JOB_CMD} in dir ${JOB_DIR}"
  cat <<EOF > /etc/init/${JOB_NAME}.conf
#!upstart
description "${JOB_NAME}"
author      "${SVC_AUTHOR}"

env PATH=/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

respawn
start on runlevel [2345]
stop on runlevel [016]

setuid $SVC_USER
chdir "${JOB_DIR}"

script
sh -l -c "${JOB_CMD} 2>&1 | tee ${LOG_DIR}/${JOB_NAME}.log"

end script
EOF
}

mkUpstart ${JOB_MONITORING} ${MMS_MONITORING_HOME} "nohup python agent.py"
mkUpstart ${JOB_BACKUP} ${MMS_BACKUP_HOME} "nohup ./mongodb-mms-backup-agent"

juju-log "Restarting ${SVC_NAME}"
startJobs
juju-log "started ${SVC_NAME}"
