#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

set -e

. $CHARM_DIR/scripts/common-variables.sh
cd /tmp

juju-log "about to install python setuptools"
apt-get install -y  python-setuptools python-dev
juju-log "easy_install pymongo"

easy_install hashlib
easy_install pymongo

# Make User
juju-log "making ${SVC_USER} user, clearing homedir contents"
mkdir -p ${MMS_HOMEDIR}
rm -rf ${MMS_HOMEDIR}/*
grep ${SVC_USER} /etc/passwd || useradd ${SVC_USER} -d ${MMS_HOMEDIR}

# pass in the expected directory and url
downloadAgent () {
  if [ -z $1 ]; then
    echo "downloadAgent needs 2 args (got zero)"
    exit 5
  fi
  if [ -z $2 ]; then
    echo "downloadAgent needs 2 args"
    exit 6
  fi
  UNPACKED_DIR=$1
  DL_URL=$2
  DL_TMPFILE=${UNPACKED_DIR}.dl.tgz
  juju-log "downloading ${UNPACKED_DIR} from ${DL_URL}"
  cd ${MMS_HOMEDIR}
  rm -rf ${DL_TMPFILE}
  rm -rf ${UNPACKED_DIR}
  curl -L -o ${DL_TMPFILE} ${DL_URL}
  TAR_DIR=$(tar ztf backup-agent.dl.tgz | head -n 1 | sed -e 's/\/.*//')
  juju-log "tar output at : ${TAR_DIR}"
  tar zxvf ${DL_TMPFILE}
  if [ ! -d ${UNPACKED_DIR} ]; then
    juju-log " mv ${TAR_DIR} ${UNPACKED_DIR} "
    mv ${TAR_DIR} ${UNPACKED_DIR}
    # juju-log "Expected mms contents at ${UNPACKED_DIR}. not there."
    # exit 1
  fi
  chown -R ${SVC_USER} ${MMS_HOMEDIR}
}

downloadAgent ${MMS_MONITORING_AGENT_UNPACKED_DIR} ${MMS_MONITORING_AGENT_URL}
downloadAgent ${MMS_BACKUP_AGENT_UNPACKED_DIR} ${MMS_BACKUP_AGENT_URL}

# rm -rf /tmp/mms.tgz
# rm -rf /tmp/${MMS_UNPACKED_DIR}
# curl -o /tmp/mms.tgz $MMS_MONITORING_AGENT_URL
# tar zxvf mms.tgz
# if [ ! -d /tmp/${MMS_UNPACKED_DIR} ]; then
#   juju-log "Expected mms contents at /tmp/${MMS_UNPACKED_DIR}. not there."
#   exit 1
# fi
# juju-log "making ${MMS_MONITORING_AGENT_URL} user"
# mkdir -p ${MMS_HOMEDIR}
# grep ${SVC_USER} /etc/passwd || useradd ${SVC_USER} -d ${MMS_HOMEDIR}
# rm -rf ${MMS_HOMEDIR}/*
# cp -r /tmp/${MMS_UNPACKED_DIR} ${MMS_HOMEDIR}/
# chown -R ${SVC_USER} ${MMS_HOMEDIR}

juju-log "Done installing mms"
